[workspace]
members = [
    "dora-studio-server/server",
    "dora-studio-server/api",
    "dora-studio-server/coordinator-client",
    "dora-studio-server/zenoh-listener",
    "dora-studio-server/otlp-listener",
    "dora-studio-server/storage",
    "dora-studio-server/core",
]
resolver = "2"

[workspace.dependencies]
axum = { version = "0.8.8", features = ["ws"] }
eyre = "0.6.12"
tokio = { version = "1.50.0", features = ["full", "rt-multi-thread"] }
uuid = { version = "1.22.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tarpc = { version = "0.37", features = ["tokio1", "serde-transport", "tcp"] }
tokio-serde = { version = "0.8", features = ["json"] }
dora-core = { git = "https://github.com/dora-rs/dora.git" }
dora-message = { git = "https://github.com/dora-rs/dora.git" }
datafusion = "52.3.0"
arrow = { version = "57.3.0", features = ["ipc"] }
parquet = { version = "57.3.0", features = ["async"] }
tonic = "0.12"
prost = "0.13"
tracing = "0.1"
tracing-subscriber = "0.3"
